# Generated by Django 3.0.7 on 2020-09-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vanshaj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='children',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='parentF',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='parentM',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='so',
        ),
    ]
