# Generated by Django 3.0.7 on 2020-07-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanshaj', '0002_auto_20200713_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='significantOther',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vanshaj.Individual'),
        ),
    ]
