# Generated by Django 3.0.7 on 2020-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanshaj', '0003_auto_20200923_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
