# Generated by Django 3.0.7 on 2020-07-14 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanshaj', '0003_auto_20200713_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
